# Generated by Django 4.2.7 on 2026-04-09 12:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('sobrenome', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('criacao_data', models.DateTimeField(default=django.utils.timezone.now)),
                ('telefone', models.CharField(max_length=15)),
                ('crm', models.CharField(max_length=6)),
                ('especialidade', models.CharField(max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('mensagem', models.TextField(blank=True)),
                ('imagem', models.ImageField(blank=True, upload_to='img/%y/%m')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sobrenome', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=15)),
                ('cpf', models.CharField(max_length=11)),
                ('criacao_data', models.DateTimeField(default=django.utils.timezone.now)),
                ('mensagem', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('imagem', models.ImageField(blank=True, upload_to='', verbose_name='img/%Y/%m')),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.DateField(default=django.utils.timezone.now)),
                ('obaservacao', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('A', 'Agendano'), ('X', 'Cancelado'), ('C', 'Confirmado'), ('R', 'Realizado')], default='A', max_length=1)),
                ('medico_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranet.medico')),
                ('paciente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranet.paciente')),
            ],
        ),
    ]
